# Generated by Django 3.2.6 on 2021-09-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='memberemail',
            field=models.EmailField(default=123, max_length=128, verbose_name='이메일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='roots',
            field=models.CharField(choices=[('c', '카페(cafe)'), ('s', '검색(search)')], default=14, max_length=1, verbose_name='가입 경로'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='아이디'),
        ),
    ]
