# Generated by Django 3.2.6 on 2021-10-02 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20210916_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine_name', models.CharField(max_length=64, verbose_name='와인명')),
                ('wine_price', models.IntegerField(verbose_name='와인 가격')),
                ('wine_photo', models.TextField(max_length=128, verbose_name='와인 사진')),
                ('wine_discribe', models.TextField(max_length=255, verbose_name='와인 설명')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='ping_num',
            field=models.IntegerField(default=0, verbose_name='핑 상태'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='teachers',
            field=models.CharField(choices=[('T', '선생님(teacher)'), ('S', '학생(student)')], default=1, max_length=1, verbose_name='선생님'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', '남성(men)'), ('W', '여성(women)')], max_length=1, verbose_name='성별'),
        ),
        migrations.CreateModel(
            name='manwine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine_num', models.IntegerField(verbose_name='구매 와인 수량')),
                ('id_user', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='member.user', verbose_name='구매자 아이디')),
                ('name_wine', models.ForeignKey(db_column='wine_name', on_delete=django.db.models.deletion.CASCADE, related_name='wine', to='member.wine', verbose_name='구매 와인')),
            ],
        ),
    ]
