# Generated by Django 3.2.6 on 2021-10-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20211002_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teachers',
            field=models.CharField(choices=[('T', '선생님(teacher)'), ('S', '학생(student)'), ('C', '손님(customer')], max_length=1, verbose_name='선생님'),
        ),
    ]
